### PR TITLE
FIx: Top portion of issue body content should not display

### LINKED ISSUE #117: Top portion of issue body content should not display
#### Issue description

When fetching issue body content from the backend, the top portion includes the YAML block front matter metadata from the GitHub issue template, which is not part of the content needed for the issue body.

#

#### Steps to reproduce the issue

1. Fetch issue body content from download_url of @api_external in the backend.
2. Observe that the top portion includes the YAML block front matter metadata from the GitHub issue template.

#

#### Expected behavior

The issue body content should not include the YAML block front matter metadata.

#

#### Screenshots

Image

Image

#

#### Additional context

Repo URL: https://github.com/collabo-community/api-server

#

#### Testing checklist

Note (to contributor taking on this task assignment): Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for.
- [ ] YAML block front matter metadata is not included in the issue body.
- [ ] Relevant issue content is displayed correctly.
- [ ] I certify that I ran my checklist

### PR DESCRIPTION
**Pull request by Oyebliss**
#### This pull request makes the following changes

* Fixes collabo-community/issue-tickets-ready-for-fixing#117

#

#### General checklist

- [x] My pull request adheres to the [Collabo Community pull request guidelines](https://docs.collabocommunity.com/pull-request-guidelines).
- [x] I have read and understood the **Pull request guideline extension** section found at the bottom of this pull request description/body.
- [x] I have replaced the dummy text under the subheading **Testing checklist** below with the testing checklist from the issue ticket I'm working on.

#

#### Testing checklist

- [x] Relevant issue content is displayed correctly.
- [x] I certify that I ran my checklist

#

#### How to run project

Their is a change at the endpoint which as now been updated.
Linked PR: https://github.com/orgs/collabo-community/projects/1/views/27?pane=issue&itemId=101002805&issue=collabo-community%7Cissue-tickets-ready-for-fixing%7C117

#

#### Pull request guideline extension

> [!NOTE]  
> Do not remove this note or section. This talks about extra things to take note of, in addition to the directions given in the Collabo Community pull request guidelines.

We appreciate the time taken to help tackle issue tickets within the Collabo Community. Please go ahead to submit your pull request even if it is not yet completed, and push to the pull request actively. This will allow us to know that you have not abandoned the issue ticket. However, you should only alert reviewers about your pull request as explained below, to avoid flooding their GitHub notifications unnecessarily.

"Ready for review" implies that things are working as expected, according to how it is specified in the issue ticket you are working on. Ensure that you test the code that you are working on, that it works as expected. Don't just request for review when your pull request is not yet done and working.

The only time you should be making people review something incomplete is: if you want to show them what's not working, so that they can send help or guidance. If this is the case, be explicit about this in our Discord community or in the comment of your pull request (after you have submitted the pull request).

### CODE REVIEW

**Comment by Oyebliss** [comment]
Hello, this PR is ready for review

File: lib/src/ui/issue_form.dart [hunk 1]
```diff
@@ -30,17 +30,16 @@ class _IssueFormState extends State<IssueForm> {
...
+        (template) => template.title == templateType,
         orElse: () => IssueTemplate(
-          name: '',
-          downloadUrl: '',
+          title: '',
+          content: '',
         ),
       );
-      final templateBody =
-          await widget.service!.fetchTemplateBody(template.downloadUrl);
```
Comment (Ifycode) [inline lib/src/ui/issue_form.dart:40]: Good that you removed the call `fetchTemplateBody`, you should also remove that `fetchTemplateBody` function from the service file too. Since we no longer need it @Oyebliss

File: lib/src/ui/issue_form.dart [hunk 2]
```diff
@@ -152,8 +151,10 @@ class _IssueFormState extends State<IssueForm> {
               ),
               items: widget.templates.map((template) {
                 return DropdownMenuItem(
-                  value: template.name,
-                  child: Text(template.name),
+                  value: template.title,
+                  child: Center(
```
Comment (Ifycode) [inline lib/src/ui/issue_form.dart]: Not such where you would have entered the text here @Oyebliss

**Review by Ifycode — CHANGES_REQUESTED** [review]

File: lib/src/ui/issue_form.dart (hunk 2 above)
Comment (Oyebliss) [reply lib/src/ui/issue_form.dart]: Sorry, i didn't get this part..

Comment (Ifycode) [reply lib/src/ui/issue_form.dart]: Sorry, I meant "centered" not "entered".

File: lib/src/ui/issue_form.dart [hunk 3]
```diff
@@ -152,13 +151,19 @@ class _IssueFormState extends State<IssueForm> {
...
+                    ),
+                  ),
                 );
               }).toList(),
               onChanged: (value) => _updateIssueBody(value),
             ),
-            const SizedBox(height: 15),
+            const SizedBox(
+              height: 15,
+            ),
```
Comment (Ifycode) [inline lib/src/ui/issue_form.dart]: Also not sure why GitHub records a change here @Oyebliss

**Review by Ifycode — CHANGES_REQUESTED** [review]

File: lib/src/ui/issue_form.dart (hunk 3 above)
Comment (Oyebliss) [reply lib/src/ui/issue_form.dart]: it was a comma i added to refactor the code,

Comment (Ifycode) [reply lib/src/ui/issue_form.dart]: It's like you want your PR to stay here for long @Oyebliss

Comment (Ifycode) [reply lib/src/ui/issue_form.dart]: Maybe you should take a look at the PR guidelines again to remind yourself of the workflow, and why this doesn't help us.

Comment (Ifycode) [reply lib/src/ui/issue_form.dart]: You can let me know when you are ready to move your PR forward.

Comment (Oyebliss) [reply lib/src/ui/issue_form.dart]: I have rectify it and ready for review

File: lib/src/ui/issue_form.dart [hunk 4]
```diff
@@ -152,8 +151,10 @@ class _IssueFormState extends State<IssueForm> {
               ),
               items: widget.templates.map((template) {
                 return DropdownMenuItem(
-                  value: template.name,
-                  child: Text(template.name),
+                  value: template.title,
+                  child: Text(
+                    template.title,
+                  ),
```
Comment (Ifycode) [inline lib/src/ui/issue_form.dart]: 1 line of code turned to 3 lines of code here @Oyebliss

**Review by Ifycode — CHANGES_REQUESTED** [review]

File: lib/src/ui/issue_form.dart (hunk 4 above)
Comment (Oyebliss) [reply lib/src/ui/issue_form.dart]: I have fixed it, ready for review

File: lib/src/ui/issue_form.dart [hunk 5]
```diff
@@ -30,17 +30,16 @@ class _IssueFormState extends State<IssueForm> {
...
         orElse: () => IssueTemplate(
-          name: '',
-          downloadUrl: '',
+          title: '',
+          content: '',
         ),
       );
-      final templateBody =
-          await widget.service!.fetchTemplateBody(template.downloadUrl);
+
```
Comment (Ifycode) [inline lib/src/ui/issue_form.dart]: Line 39 shows up as space, remove the space so that it doesn't compete with actual code change  @Oyebliss

**Review by Ifycode — CHANGES_REQUESTED** [review]

File: lib/src/ui/issue_form.dart (hunk 5 above)
Comment (Oyebliss) [reply lib/src/ui/issue_form.dart]: Done

**Review by Ifycode — APPROVED** [review]
Nicely done  🎉
